# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_PPXUV.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(703, 594)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tB_Directory = QtWidgets.QTextBrowser(self.centralwidget)
        self.tB_Directory.setGeometry(QtCore.QRect(110, 20, 551, 51))
        self.tB_Directory.setObjectName("tB_Directory")
        self.pB_open = QtWidgets.QPushButton(self.centralwidget)
        self.pB_open.setGeometry(QtCore.QRect(20, 27, 81, 41))
        self.pB_open.setObjectName("pB_open")
        self.tB_results = QtWidgets.QTextBrowser(self.centralwidget)
        self.tB_results.setGeometry(QtCore.QRect(30, 320, 641, 101))
        self.tB_results.setObjectName("tB_results")
        self.pB_convert = QtWidgets.QPushButton(self.centralwidget)
        self.pB_convert.setGeometry(QtCore.QRect(560, 490, 110, 41))
        self.pB_convert.setObjectName("pB_convert")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(100, 130, 281, 80))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(150, 40, 41, 21))
        self.label_2.setObjectName("label_2")
        self.sB_start = QtWidgets.QSpinBox(self.groupBox)
        self.sB_start.setGeometry(QtCore.QRect(60, 38, 71, 24))
        self.sB_start.setMinimum(1)
        self.sB_start.setObjectName("sB_start")
        self.sB_End = QtWidgets.QSpinBox(self.groupBox)
        self.sB_End.setGeometry(QtCore.QRect(200, 38, 71, 24))
        self.sB_End.setMinimum(1)
        self.sB_End.setProperty("value", 10)
        self.sB_End.setObjectName("sB_End")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 40, 41, 21))
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(100, 220, 561, 81))
        self.groupBox_2.setObjectName("groupBox_2")
        self.sB_low = QtWidgets.QSpinBox(self.groupBox_2)
        self.sB_low.setGeometry(QtCore.QRect(70, 40, 81, 24))
        self.sB_low.setMaximum(511)
        self.sB_low.setProperty("value", 200)
        self.sB_low.setObjectName("sB_low")
        self.sB_high = QtWidgets.QSpinBox(self.groupBox_2)
        self.sB_high.setGeometry(QtCore.QRect(200, 40, 81, 24))
        self.sB_high.setMaximum(511)
        self.sB_high.setProperty("value", 300)
        self.sB_high.setObjectName("sB_high")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 42, 41, 21))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(160, 42, 41, 21))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(310, 42, 71, 21))
        self.label_5.setObjectName("label_5")
        self.dsB_thrhld = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.dsB_thrhld.setGeometry(QtCore.QRect(380, 40, 71, 24))
        self.dsB_thrhld.setDecimals(4)
        self.dsB_thrhld.setMaximum(1.0)
        self.dsB_thrhld.setSingleStep(0.001)
        self.dsB_thrhld.setProperty("value", 0.004)
        self.dsB_thrhld.setObjectName("dsB_thrhld")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 430, 251, 80))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pB_save = QtWidgets.QPushButton(self.groupBox_3)
        self.pB_save.setGeometry(QtCore.QRect(130, 30, 110, 41))
        self.pB_save.setObjectName("pB_save")
        self.pB_reload = QtWidgets.QPushButton(self.groupBox_3)
        self.pB_reload.setGeometry(QtCore.QRect(10, 30, 110, 41))
        self.pB_reload.setObjectName("pB_reload")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(310, 450, 351, 31))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.tE_header = QtWidgets.QTextEdit(self.centralwidget)
        self.tE_header.setGeometry(QtCore.QRect(110, 85, 551, 31))
        self.tE_header.setObjectName("tE_header")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 90, 71, 21))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 703, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pB_open.setText(_translate("MainWindow", "Open"))
        self.pB_convert.setText(_translate("MainWindow", "convert"))
        self.groupBox.setTitle(_translate("MainWindow", "Run Start & End"))
        self.label_2.setText(_translate("MainWindow", "End:"))
        self.label.setText(_translate("MainWindow", "Start:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Treming conditions"))
        self.label_4.setText(_translate("MainWindow", "Start:"))
        self.label_3.setText(_translate("MainWindow", "End:"))
        self.label_5.setText(_translate("MainWindow", "threshold:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Save/Reload"))
        self.pB_save.setText(_translate("MainWindow", "Save"))
        self.pB_reload.setText(_translate("MainWindow", "Reload"))
        self.label_6.setText(_translate("MainWindow", "File Header:"))

